name: qr_offline_sync
description: "A new Flutter project."

version: 1.0.0+2

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  mobile_scanner: ^7.2.0
  camera: ^0.12.0+1
  drift: ^2.34.0
  dio: ^5.9.2
  connectivity_plus: ^7.1.1
  permission_handler: ^12.0.3
  flutter_blue_plus:
  sqflite: ^2.4.2+1
  fluttertoast: ^9.1.0
  path: ^1.9.1
  shared_preferences: ^2.5.5
  firebase_core: ^4.11.0
  firebase_crashlytics: ^5.2.4
  workmanager: ^0.9.0+3
  device_info_plus: ^13.2.0
  geolocator:
  intl:
  geocoding: ^5.0.0
  flutter_native_splash: ^2.4.7
#  usb_serial:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#023020"
  adaptive_icon_foreground: assets/icon/app_icon.png


flutter_native_splash:
  color: "#023020"       # Your hex color code
  color_dark: "#023020"  # Optional: Background color for dark mode

  # Android 12+ specific settings
  android_12:
    icon_background_color: "#023020"
    icon_background_color_dark: "#023020"

flutter:
  uses-material-design: true

  assets:
    - assets/icon/app_icon.png